const q1 = "GOOD THINGS COME TO THOSE WHO SWEAT";
const q2 = "HUSTLE FOR THAT MUSCLE";
const q3 = "PUSH HARDER THAN YESTERDAY IF YOU WANT A DIFFERENT TOMORROW";
const q5 = "RESULTS HAPPEN OVERTIME, NOT OVERNIGHT. BE PATIENT";
const q6 = "IT COMES DOWN TO ONE SIMPLE THING: HOW BAD DO YOU WANT IT?";
const q7 = "WORKOUT IS HARD, BEING FAT IS HARD, PICK YOUR HARD";
const q8 = "IF IT DOESN'T CHALENGE YOU, IT DOESN'T CHANGE YOU";
const q9 = "NOT EVERY IS A GOOD DAY. SHOW UP ANYWAY!";

const quotes = [q1, q2, q3, q4, q5, q6, q7, q8, q9];


